name: alerts
description: Balagh Amen - Professional Alert Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Database - Versions ajustées pour compatibilité maximale avec votre SDK
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  sqflite_common_ffi_web: ^1.0.1
  path_provider: ^2.1.2
  path: ^1.9.0

  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  image_picker: ^1.1.2
  file_picker: ^8.0.3
  url_launcher: ^6.3.1
  crypto: ^3.0.3
  geolocator: ^13.0.2
  intl: ^0.20.2
  open_filex: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# ✅ CONFIGURATION PROFESSIONNELLE ET ADAPTATIVE
flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icone.png" # Icône pour iOS et anciens Android
  
  # Configuration Adaptative (Android 8.0+)
  # Cela va supprimer les bords noirs et rendre l'icône "Pleine"
  adaptive_icon_background: "#7B1111" # Le Bordeaux exact de votre logo
  adaptive_icon_foreground: "assets/icone.png" # Votre logo au centre
  
  # Web
  web:
    generate: true
    image_path: "assets/icone.png"
    background_color: "#7B1111"
    theme_color: "#7B1111"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
